- .dockerignore
- .gitignore
- docker/rpi/Dockerfile
- rpi_requirements.txt
Installs scikit-learn from apt instead of pip to save build time
> installs scikit-learn from apt

- src/lib/detectors/edgetpu/__init__.py
Tries to load EdgeTPU via USB first. If this fails, try again but with PCIe
Closes #41
> try to load EdgeTPU PCIe if USB is not found

- src/lib/detectors/edgetpu/__init__.py
> fix loading edgetpu

- src/lib/camera.py
> fix codec issues

- src/lib/mqtt/__init__.py
Logs MQTT connection errors in clear-text. Closes #59
> log connection errors

- Dockerfile
- docker/cuda/Dockerfile
- docker/rpi/Dockerfile
- docker/vaapi/Dockerfile
> install tzdata

- README.md
- src/lib/config/config_recorder.py
- src/lib/mqtt/camera.py
- src/lib/nvr.py
- src/lib/recorder.py
> add option to save thumbnail to disk/mqtt

- src/viseron.py
Sets up cameras in parallel, this significantly reduces the time it takes for a full restart
> parallel setup of cameras

- src/lib/detectors/edgetpu/__init__.py
> print error message when loading edgetpu

- src/lib/recorder.py
> fix thumbnail saving to disk

- src/lib/recorder.py
> fix folder name

- src/lib/nvr.py
> fix crash when mqtt not configured

- README.md
- src/lib/config/config_object_detection.py
- src/lib/detector.py
- src/lib/helpers.py
- src/lib/nvr.py
- src/lib/zones.py
Adds `require_motion`. Closes #129
> add require_motion config option

- viseron/cleanup.py
> catch exception on segment cleanup

- viseron/cleanup.py
- viseron/segments.py
Use with instead of acquire/release to prevent deadlock
Catch exceptions in concat command
> fix segments script to work with newest ffmpeg

- README.md
- viseron/__init__.py
- viseron/camera/__init__.py
- viseron/camera/frame.py
- viseron/camera/frame_decoder.py
- viseron/camera/stream.py
- viseron/cleanup.py
- viseron/config/config_camera.py
- viseron/const.py
- viseron/data_stream.py
- viseron/detector/__init__.py
- viseron/motion.py
- viseron/nvr.py
- viseron/post_processors/__init__.py
- viseron/thread_watchdog.py
- viseron/webserver/__init__.py
This pull adds the RestartableThread class along with ThreadWatchdog.
These classes combined makes it possible to monitor any long running process and restart them incase of an exception.
There is also a timeout feature in the watchdog which restarts a thread if it has not updated a timer in a while
> Thread watchdog

- README.md
- viseron/config/config_recorder.py
- viseron/recorder.py
Allow users to supply their own strftime pattern for recorder and thumbnail filenames.
Closes #182
> add filename_pattern config option

- viseron/helpers/__init__.py
- viseron/nvr.py
- viseron/zones.py
> fix require_motion when used in zones

- docker/amd64-cuda/Dockerfile.ffmpeg
- docker/amd64-cuda/Dockerfile.opencv
> support CUDA compute capability 3.5 and higher

- viseron/nvr.py
> object with require_motion shouldnt start recorder

- docker/Dockerfile
- docker/amd64-cuda/Dockerfile.dlib
- docker/amd64/Dockerfile.dlib
- docker/jetson-nano/Dockerfile.dlib
- docker/jetson-nano/Dockerfile.wheels
- docker/rpi3/Dockerfile.dlib
- requirements.txt
install face_recognition in wheels docker image
> pin numpy and install scikit-learn from pip

- docker/Dockerfile
- docker/amd64-cuda/Dockerfile.dlib
- docker/amd64/Dockerfile.dlib
- docker/jetson-nano/Dockerfile.dlib
- docker/jetson-nano/Dockerfile.wheels
- docker/rpi3/Dockerfile.dlib
- requirements.txt
Reverts roflcoopter/viseron#245
> Revert "pin numpy and install scikit-learn from pip"

- viseron/camera/stream.py
Fix deadlock caused by #274 
Closes #299
> resolve deadlock when using substream

- viseron/components/webserver/stream_handler.py
I found another one so I refactored some code
> Add new line to jpg boundary refactoring

- docker/jetson-nano/Dockerfile.darknet
- docker/jetson-nano/Dockerfile.dlib
- docker/jetson-nano/Dockerfile.ffmpeg
- docker/jetson-nano/Dockerfile.opencv
- docker/jetson-nano/Dockerfile.opencv.part1
- docker/jetson-nano/Dockerfile.python
- docker/jetson-nano/Dockerfile.wheels
> fix jetson nano crossbuilds after balenalib breaking change

- viseron/helpers/logs.py
Removal of dead code using vulture broke the custom logpipes. This PR reverts that
> add back accidentally removed code

- rootfs/etc/cont-init.d/30-edgetpu-permission
Fix permission issue when plugdev group is missing in the container
> make sure user abc is always in plugdev group

- docs/src/pages/components-explorer/components/compreface/_meta.tsx
- docs/src/pages/components-explorer/components/compreface/config.json
- docs/src/pages/components-explorer/components/compreface/index.mdx
- requirements.txt
- viseron/components/compreface/__init__.py
- viseron/components/compreface/const.py
- viseron/components/compreface/face_recognition.py
- viseron/domains/face_recognition/__init__.py
- viseron/domains/face_recognition/binary_sensor.py
- viseron/domains/face_recognition/const.py
Add Compreface component which adds another face recognition module
> add compreface component

- viseron/components/edgetpu/__init__.py
Pretrained image classifier models have unique input quantization values and require additional preprocessing.
Increase confidence levels by a lot
Closes #312
> perform preprocessing for quantized classifier models

- viseron/domains/object_detector/binary_sensor.py
- viseron/domains/object_detector/detected_object.py
> add list of objects to object detector binary sensors

- docker/amd64-cuda/Dockerfile.base
- docker/amd64/Dockerfile.base
> install more VAAPI drivers

- docs/src/pages/components-explorer/components/edgetpu/config.json
- viseron/components/edgetpu/config.py
- viseron/components/edgetpu/const.py
- viseron/components/edgetpu/image_classification.py
> improve accuracy of image classifier

- docs/src/components/HomepageFeatures.tsx
Fix broken link to Components Explorer
> Fix broken link

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/CardActionButton.tsx
- frontend/src/components/ScrollToTop.tsx
- frontend/src/components/footer/Footer.tsx
- frontend/src/components/header/Breadcrumbs.tsx
- frontend/src/components/header/Drawer.tsx
- frontend/src/components/header/Header.tsx
- frontend/src/components/recording/RecordingCard.tsx
- frontend/src/components/recording/RecordingCardDaily.tsx
- frontend/src/components/recording/RecordingCardLatest.tsx
- frontend/src/components/videoplayer/VideoPlayer.tsx
- frontend/src/components/videoplayer/VideoPlayerPlaceholder.tsx
- frontend/src/context/ColorModeContext.tsx
- frontend/src/lib/helpers.ts
- frontend/src/pages/Cameras.tsx
- frontend/src/pages/recordings/CameraRecordings.tsx
- frontend/src/pages/recordings/CameraRecordingsDaily.tsx
- frontend/src/pages/recordings/Recordings.tsx
Groups recordings per day instead of showing them all in one long list.
Consolidates the look of all grids
Adds a floating scroll to top button
> Group recordings per day

- tests/components/ffmpeg/test_stream.py
- viseron/components/ffmpeg/camera.py
- viseron/components/ffmpeg/stream.py
- viseron/components/gstreamer/camera.py
- viseron/domains/camera/__init__.py
- viseron/domains/camera/recorder.py
Fix error when concatenating segments when `mkv` has been automatically selected
> fix extension when automatically switching to mkv

- viseron/helpers/__init__.py
> catch exception when drawing text on mask

- viseron/components/gstreamer/pipeline.py
> set correct parsing element from predefined map

- tests/common.py
- tests/components/ffmpeg/test_stream.py
- viseron/components/ffmpeg/camera.py
- viseron/components/ffmpeg/stream.py
The change in #428  seems to cause trouble instead of helping, so i am changing the behavior to transcoding the audio instead of overriding the file extension
> transcode audio to aac instead of changing to mkv

- frontend/src/App.tsx
- frontend/src/components/CardActionButton.tsx
- frontend/src/components/editor/Editor.tsx
- frontend/src/components/error/Error.tsx
- frontend/src/components/footer/Footer.tsx
- frontend/src/components/header/Drawer.tsx
- frontend/src/components/loading/Loading.tsx
- frontend/src/hooks/UseToast.tsx
- frontend/src/index.tsx
- frontend/src/lib/helpers.tsx
- frontend/src/lib/messages.ts
- frontend/src/pages/Cameras.tsx
- frontend/src/pages/recordings/Recordings.tsx
- viseron/components/webserver/api/v1/auth.py
- viseron/components/webserver/websocket_api/commands.py
Reduces bundle size by about 50%, making initial load faster
> Reduce bundle size

- .devcontainer/devcontainer.json
- docker/Dockerfile.dev
- docs/docs/contributing.mdx
- docs/docs/developers.mdx
- docs/docs/developers/backend.mdx
- docs/docs/developers/backend/components.mdx
- docs/docs/developers/backend/create_component.mdx
- docs/docs/developers/backend/data_stream_component.mdx
- docs/docs/developers/backend/domains.mdx
- docs/docs/developers/backend/entities.mdx
- docs/docs/developers/backend/events.mdx
- docs/docs/developers/backend/vis_object.mdx
- docs/docs/developers/development_environment/pull_request.mdx
- docs/docs/developers/development_environment/setup.mdx
- docs/docs/developers/development_environment/style_guidelines.mdx
- docs/docs/developers/docker.mdx
- docs/docs/developers/docs.mdx
- docs/docs/developers/frontend.mdx
- docs/docs/documentation.md
- docs/docs/documentation/configuration.md
- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- docs/sidebars.js
- frontend/src/components/header/Drawer.tsx
Adds some developer documentation that explains how to use the Devcontainer.
The developer documentation as a whole is still mostly placeholders
> add initial developer documentation

- docs/docs/developers/frontend/proxy.mdx
- docs/sidebars.js
- frontend/vite.config.ts
Add some notes on how to run the frontend locally
> add frontend proxy docs

- viseron/helpers/__init__.py
INTER_AREA gives higher quality images
> resize using INTER_AREA instead of INTER_CUBIC

- docker/rpi3/Dockerfile.base
> include yolov7 model in rpi3/armv7 image

- rootfs/etc/cont-init.d/30-edgetpu-permission
> improve logging for pcie startup scripts

- viseron/components/ffmpeg/camera.py
- viseron/components/ffmpeg/segments.py
> allow audio codec to be null

- .github/workflows/ci.yaml
- requirements_ci.txt
- viseron/components/gstreamer/const.py
- viseron/components/gstreamer/stream.py
Install Gstreamer in the CI pipeline in order for the Check generated docs step to pass
> install gst/gi in ci

- viseron/components/ffmpeg/segments.py
Refactor out recorder audio codec logic
> fix recorder audio codec not being set

- docs/src/pages/components-explorer/components/ffmpeg/config.json
- docs/src/pages/components-explorer/components/ffmpeg/index.mdx
- viseron/components/ffmpeg/camera.py
- viseron/components/ffmpeg/const.py
- viseron/components/ffmpeg/stream.py
- viseron/components/gstreamer/camera.py
Allow for a workaround in https://github.com/roflcoopter/viseron/issues/625
> add ffmpeg raw_command option

- viseron/domains/motion_detector/__init__.py
> copy frames to avoid clash for motion detection

- .github/templates/run_in_venv/action.yaml
- .github/workflows/ci.yaml
- .gitignore
- .pre-commit-config.yaml
Attempt to fix the error "bad interpreter: No such file or directory" which surfaces randomly
> attempt to fix sporadic error in ci

- rootfs/etc/cont-init.d/40-set-env-vars
- viseron/components/storage/queries.py
Change how available timestamps are fetched to avoid crash
Sets HOME environment variable to remove gpac errors when not running as root
> Available timespan safguard

- azure-pipelines/templates/build.yaml
- docker/Dockerfile
Add Viseron version into the image at build time
> inject viseron version in docker container

- docker/Dockerfile
- rootfs/etc/cont-init.d/40-set-env-vars
- tests/components/storage/test_tier_handler.py
- tests/components/webserver/common.py
- viseron/__init__.py
- viseron/components/storage/tier_handler.py
- viseron/components/webserver/__init__.py
- Make sure to instantly delete files instead of moving them to succeeding tiers that wont store them
- Crossbuild gpac so it works on aarch64, jetson-nano etc
- Make sure jetson-nano finds the correct postgresql version
> Delete files instead of moving them

- docs/src/pages/components-explorer/components/codeprojectai/config.json
- docs/src/pages/components-explorer/components/compreface/config.json
- docs/src/pages/components-explorer/components/deepstack/config.json
- docs/src/pages/components-explorer/components/dlib/config.json
- viseron/components/codeprojectai/face_recognition.py
- viseron/components/compreface/face_recognition.py
- viseron/components/deepstack/face_recognition.py
- viseron/components/dlib/face_recognition.py
- viseron/components/nvr/nvr.py
- viseron/components/storage/alembic/versions/8462ca6851b2_add_postprocessorresults_table.py
- viseron/components/storage/models.py
- viseron/components/webserver/api/v1/camera.py
- viseron/domains/camera/__init__.py
- viseron/domains/camera/shared_frames.py
- viseron/domains/face_recognition/__init__.py
- viseron/domains/face_recognition/const.py
- viseron/domains/image_classification/__init__.py
- viseron/domains/license_plate_recognition/__init__.py
- viseron/domains/object_detector/__init__.py
- viseron/domains/post_processor/__init__.py
- viseron/helpers/__init__.py
- Store snapshots for face recognition
- Keep frames in memory as long as post processors require them
> Face recognition snapshots

- docker/Dockerfile
- viseron/domains/camera/fragmenter.py
- Make sure segments are deleted in all cases
- Fix a typo in the Dockerfile
> Properly delete segments

- tests/common.py
- tests/components/codeprojectai/test_object_detector.py
- tests/conftest.py
- viseron/__init__.py
- viseron/components/codeprojectai/object_detector.py
- viseron/exceptions.py
> fix codeprojectai object detection when running with no image_size

- frontend/src/components/events/EventPlayerCard.tsx
- frontend/src/components/events/SyncManager.tsx
- frontend/src/components/events/timeline/TimelinePlayer.tsx
- frontend/src/components/events/utils.tsx
- frontend/src/hooks/UseControlledInterval.tsx
Displays HLS errors as an overlay for each camera feed
> display HLS errors to clearly indicate why a player gets paused

- frontend/src/components/recording/RecordingCard.tsx
- frontend/src/components/recording/RecordingCardLatest.tsx
- frontend/src/lib/types.ts
- frontend/tests/lib/helpers.test.ts
- tests/domains/camera/test_recorder.py
- viseron/components/storage/models.py
- viseron/domains/camera/recorder.py
> correctly fetch recordings in the clients timezone

- tests/components/webserver/api/v1/test_events.py
- tests/domains/camera/test_fragmenter.py
- tests/domains/camera/test_recorder.py
- tests/helpers/test__init__.py
- viseron/components/storage/models.py
- viseron/components/storage/queries.py
- viseron/components/webserver/api/v1/events.py
- viseron/components/webserver/api/v1/hls.py
- viseron/components/webserver/api/v1/recordings.py
- viseron/components/webserver/auth.py
- viseron/components/webserver/websocket_api/commands.py
- viseron/domains/camera/fragmenter.py
- viseron/domains/camera/recorder.py
- viseron/helpers/__init__.py
Make sure all datetime objects are in UTC
> unified timezone handling

- tests/components/ffmpeg/test_stream.py
- viseron/components/ffmpeg/stream.py
> set rtsp_transport for ffprobe

- frontend/src/components/events/EventDatePickerDialog.tsx
- frontend/src/components/events/utils.tsx
- frontend/src/lib/commands.ts
- frontend/src/lib/messages.ts
- frontend/src/lib/types.ts
- frontend/src/lib/websockets.ts
- frontend/tests/components/events/EventDatePicker.test.tsx
- viseron/components/webserver/websocket_api/commands.py
> allow dates with only recorded video to be selected

- viseron/components/storage/tier_handler.py
> use yield_per to avoid cursor closing in _check_tier

- viseron/domains/camera/shared_frames.py
- viseron/domains/motion_detector/__init__.py
- viseron/domains/object_detector/__init__.py
- viseron/helpers/__init__.py
- viseron/helpers/decorators.py
- viseron/helpers/filter.py
> apply object detection mask the same way as motion detection

- viseron/components/ffmpeg/stream.py
> fix ffmpeg log pipe closing

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/error/ErrorMessage.tsx
- frontend/src/index.tsx
Add two error boundaries to the frontend to nicely display any uncaught exceptions
> add error boundaries to frontend

- docs/src/pages/components-explorer/_components/ComponentCard/index.tsx
> Component explorer link fix

- docs/src/pages/components-explorer/components/ptz/_meta.tsx
- docs/src/pages/components-explorer/components/telegram/_meta.tsx
- viseron/components/telegram/__init__.py
- viseron/domains/camera/recorder.py
Small follow up changes for #788
> Fixes to the new PTZ and Telegram components

- viseron/helpers/__init__.py
> fix mask image coordinates being reversed

- docs/src/pages/components-explorer/components/ffmpeg/index.mdx
> update docs on how to add timestamp to recorded video

- viseron/components/compreface/__init__.py
- viseron/components/compreface/face_recognition.py
- viseron/components/webserver/api/v1/compreface.py
#845 created some regression when not setting `use_subjects`
This PR fixes that.
Closes #956
> better handling of compreface initialization

- viseron/components/ptz/__init__.py
- viseron/helpers/__init__.py
Dynamically find the path to devicemgmt.wsdl
Closes #986
> ptz: find location of .wsdl file

- docs/src/pages/components-explorer/components/edgetpu/config.json
- docs/src/pages/components-explorer/components/edgetpu/index.mdx
- viseron/components/edgetpu/__init__.py
- viseron/components/edgetpu/config.py
- viseron/components/edgetpu/const.py
- viseron/components/edgetpu/edgetpu_subprocess.py
The `edgetpu` component can now utilize multiple devices.
Closes #746
> implement EdgeTPU support for multiple devices

- viseron/components/ffmpeg/camera.py
- viseron/components/ffmpeg/stream.py
- viseron/components/gstreamer/stream.py
- viseron/helpers/__init__.py
Read frames from camera in a subprocess to avoid blocking the main process when using many cameras at high FPS
> read frames in subprocess

- tests/domains/camera/test_fragmenter.py
- viseron/domains/camera/fragmenter.py
- viseron/helpers/child_process_worker.py
- viseron/helpers/logs.py
This PR moves the segments processing to a separate process per camera.
This improves performance slightly by offloading the main process, removing some IO
> run fragmenter in subprocess

- docker/rpi3/Dockerfile.base
> copy coco.names to rpi image

- docs/src/pages/components-explorer/components/go2rtc/config.json
- docs/src/pages/components-explorer/components/go2rtc/index.mdx
- viseron/components/go2rtc/const.py
> go2rtc component doc updates

- docs/src/pages/components-explorer/components/webhook/_meta.tsx
- docs/src/pages/components-explorer/components/webhook/config.json
- docs/src/pages/components-explorer/components/webhook/index.mdx
- scripts/gen_docs/__main__.py
- viseron/components/webhook/__init__.py
- viseron/components/webhook/const.py
- viseron/helpers/validators.py
This PR introduces a new component webhook which allows users to configure event listeners and call a URL with a templatable payload.
Documentation on how do to templating will come in a follow up PR.
Related to #1058
> implement webhook component

- viseron/components/ffmpeg/camera.py
> fix race condition when stopping and starting a camera rapidly

- .gitignore
- azure-pipelines/templates/build.yaml
- docker/Dockerfile
- docker/Dockerfile.wheels
- docker/aarch64/Dockerfile.dlib
- docker/aarch64/Dockerfile.ffmpeg
- docker/aarch64/Dockerfile.opencv
- docker/azure-agent-start.sh
- docker/jetson-nano/Dockerfile.darknet
- docker/jetson-nano/Dockerfile.dlib
- docker/jetson-nano/Dockerfile.ffmpeg
- docker/jetson-nano/Dockerfile.opencv
- docker/jetson-nano/Dockerfile.opencv.part1
- docker/jetson-nano/Dockerfile.python
- docker/jetson-nano/Dockerfile.wheels
- docker/rpi5/Dockerfile.azure
Utilize a self hosted aarch64 build agent in Azure Pipelines, reducing the need for crossbuilding.
The Dockerfiles have been updated to dynamically enable crossbuilding depending on the host platform
> Azure pipelines self hosted agent
