roflcoopter/viseron

- docker/rpi/Dockerfile
- docker/rpi/Dockerfile.ffmpeg
- src/const.py
- src/lib/camera.py
- src/lib/config/config_camera.py
Uses ffprobe to get stream information.
This also makes the default codec picker a little smarter, previously it would always grab h264 version, but now a codec map is supplied so we can choose an appropriate codec for both h264/h265. In the future this could be expanded to include more codecs
> use ffprobe to get codec information

- src/lib/helpers.py
Small fix for an error that occurred during troubleshooting of #62 which made Viseron crash when MQTT was not configured
> fix error when mqtt is not configured

- src/lib/segments.py
Encodes segments to /tmp. Closes #49
> encode to tmp then move do destination

- src/lib/camera.py
I try to rotate my camera image, but when I set `filter_args` I don't see them end up in the generated `ffmpeg` command.
My config:
```
cameras:
- name: Ute
mqtt_name: ute
host: 192.168.0.*
port: 554
username: **
password: "**"
path: '/h264'
width: 2592
height: 1944
fps: 5
publish_image: true
filter_args:
- "-vf"
- "rotate=45*PI/180"
```
Output from the log:
```
[2021-03-19 21:44:35] [lib.camera.ute          ] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -c:v h264_cuvid -rtsp_transport tcp -i rtsp://*..*@192.168.0.*:554/h264 -f segment -segment_time 5 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c …
```
> Add missing option - filter_args?

- README.md
- viseron/camera/stream.py
- viseron/config/config_camera.py
- viseron/config/config_recorder.py
Allow `audio_codec` in camera config to fix crash when `width`, `height`, `fps` and `codec` was specified
> allow audio_codec in camera config

- viseron/camera/__init__.py
- viseron/config/__init__.py
- viseron/config/config_camera.py
- viseron/config/config_motion_detection.py
- viseron/config/config_object_detection.py
- viseron/detector/__init__.py
- viseron/helpers/filter.py
- viseron/helpers/logs.py
- viseron/helpers/validators.py
- viseron/nvr.py
- viseron/zones.py
This introduces a new config option under `motion_detection`, `trigger_recorder` which will start the recorder when motion is detected.
`triggers_recording` for labels is now called `trigger_recorder`.
There is also another config option available under `object_detection`, `enable` which you can set to `false` to disable object detection altogether and save some resources.
Closes #115, #149
> Motion trigger recorder

- viseron/components/webserver/stream_handler.py
```
curl -i http://viseron:8888/camera_one/mjpeg-stream --output -
HTTP/1.1 200 OK
Server: TornadoServer/6.1
Content-Type: multipart/x-mixed-replace;boundary=--jpgboundary
Date: Thu, 23 Jun 2022 08:35:10 GMT
Connection: close
Transfer-Encoding: chunked
--jpgboundaryContent-type: image/jpeg
Content-length: 3927190
```
this caused safari to render page as text not JPG
> Add newline after jpgboundary

- azure-pipelines/azure-pipelines-wheels.yml
Viseron dlib pipeline hs been renamed to Viseron tools in Azure
> fix automatic pipeline trigger error after rename

- tests/helpers/test__init__.py
- viseron/helpers/__init__.py
Fix bug which caused bounding boxes to have wrong offset on non padded axis when image was letterboxed resized
> scale the non-padded axis

- docker/jetson-nano/Dockerfile.base
- docker/jetson-nano/Dockerfile.dlib
dlib statically links libpng if it cant be found which does not work when running multi stage docker builds
Closes #403
> install libpng-dev in jetson nano dlib and base

- viseron/domains/object_detector/detected_object.py
When an object is detected close to the edge of the frame, the calculated relative coordinates could sometimes get low negative values.
This causes exceptions in post processors when they try to crop the image according to the bounding box.
The fix is to set negative coords to zero
> return zero for negative coordinates

- tests/components/gstreamer/__init__.py
- tests/components/gstreamer/test_segments.py
- viseron/components/ffmpeg/recorder.py
- viseron/components/ffmpeg/segments.py
- viseron/components/gstreamer/recorder.py
- viseron/components/gstreamer/segments.py
- viseron/components/nvr/nvr.py
If a new recording started while concatenation of segments from a previous recording was still running, it could lead to segments being deleted when they shouldnt be.
This PR adds some extra fail safes to try and prevent that.
Discussed in this thread #403
> make sure segments are not deleted during concat

- tests/common.py
- tests/components/ffmpeg/__init__.py
- tests/components/ffmpeg/test_stream.py
- viseron/components/ffmpeg/stream.py
FFmpeg does not support audio codecs pcm_alaw or pcm_mulaw in mp4 container.
Switch automatically to mkv if stream uses these codecs.
> switch to mkv for certain audio codecs

- docs/docusaurus.config.js
I noticed a couple of mis-types of `roflcoopter` as `roflcooter`.
Thanks for the great project!
> Fix a couple typos

- frontend/src/components/CameraCard.tsx
- frontend/src/components/CardActionButton.tsx
- frontend/src/components/recording/RecordingCard.tsx
- frontend/src/components/recording/RecordingCardDaily.tsx
- frontend/src/components/recording/RecordingCardLatest.tsx
- frontend/src/components/videoplayer/VideoPlayer.tsx
- frontend/src/context/ViseronContext.tsx
- frontend/src/lib/commands.ts
- frontend/src/lib/types.ts
- frontend/src/lib/websockets.ts
- frontend/src/pages/Cameras.tsx
- frontend/src/pages/recordings/Recordings.tsx
- tests/components/gstreamer/test_segments.py
- viseron/components/ffmpeg/camera.py
- viseron/components/ffmpeg/recorder.py
- viseron/components/ffmpeg/segments.py
- viseron/components/gstreamer/camera.py
- viseron/components/gstreamer/recorder.py
- viseron/components/gstreamer/segments.py
- viseron/domains/camera/const.py
- viseron/domains/camera/entity/binary_sensor.py
- viseron/domains/camera/entity/image.py
- viseron/domains/camera/recorder.py
We now subscribe to new recordings, which makes it possible to load new recordings without refreshing the page.
Also makes the layout a bit more consistent when a camera has no recordings
> Show new recordings without refreshing

- docker/amd64/Dockerfile.base
- docker/jetson-nano/Dockerfile.base
- docs/src/pages/components-explorer/components/darknet/index.mdx
Since OpenCV 4.6.0 supports YOLOv7 we can now use it as default for all models
> use yolov7 as default for all images

- docs/src/pages/components-explorer/components/background_subtractor/config.json
- docs/src/pages/components-explorer/components/mog2/config.json
- viseron/components/nvr/nvr.py
- viseron/domains/motion_detector/const.py
Also adds the possibility to set max_recorder_keepalive to 0 to turn of the functionality of max_recorder_keepalive
> fix max_recorder_keepalive when running without object detector

- viseron/components/webserver/stream_handler.py
use a tuple to separate streams with same name into the respective cameras.
fixes #462 .
> change stream dict to tuples.

- tests/components/ffmpeg/test_stream.py
- viseron/components/ffmpeg/camera.py
- viseron/components/ffmpeg/stream.py
- viseron/components/gstreamer/camera.py
- viseron/components/gstreamer/pipeline.py
- viseron/components/gstreamer/stream.py
- viseron/exceptions.py
This PR will address the FFprobeError problem (Viseron not trying to reconnect to cameras if they are unavailable during restart) outlined in this issue: #466
> raise DomainNotReady on FFProbe error/timeout

- .github/workflows/ci.yaml
- docs/src/pages/components-explorer/_components/ComponentConfiguration/index.tsx
- docs/src/pages/components-explorer/components/ffmpeg/config.json
- docs/src/pages/components-explorer/components/gstreamer/config.json
- frontend/src/components/camera/CameraCard.tsx
- frontend/src/lib/types.ts
- requirements.txt
- viseron/__init__.py
- viseron/components/webserver/api/v1/camera.py
- viseron/domains/camera/__init__.py
- viseron/domains/camera/const.py
Adds the possibility to fetch the still image directly from a URL instead of taking it from the stream using `still_image`.
Also adds the ability to refresh the image in the frontend faster using `refresh_interval`
> add new config option for still image

- docs/docs/documentation/installation.mdx
Currently the documentation links to `nvidia-docker`. However, this has been replaced by `nvidia-container-toolkit`. This PR updates the link and text accordingly.
> Update NVIDIA link on installation doc

- .gitignore
- config/.gitignore
> add empty config folder to allow devcontainer to start

- tests/components/webserver/api/test_handlers.py
- viseron/components/data_stream/__init__.py
- viseron/components/webserver/__init__.py
- viseron/components/webserver/api/handlers.py
- viseron/components/webserver/api/v1/auth.py
- viseron/components/webserver/api/v1/camera.py
- viseron/components/webserver/api/v1/cameras.py
- viseron/components/webserver/api/v1/compreface.py
- viseron/components/webserver/api/v1/config.py
- viseron/components/webserver/api/v1/events.py
- viseron/components/webserver/api/v1/hls.py
- viseron/components/webserver/api/v1/onboarding.py
- viseron/components/webserver/api/v1/recordings.py
- viseron/components/webserver/request_handler.py
- viseron/components/webserver/stream_handler.py
- viseron/components/webserver/tiered_file_handler.py
- viseron/components/webserver/websocket_api/__init__.py
- viseron/components/webserver/websocket_api/commands.py
- viseron/components/webserver/websocket_api/messages.py
All websocket commands are now fully async, which dramatically increases performance.
There are still some heavy database queries that needs to be tuned before the websocket API works really well.
The PR also includes some fixes in the REST API to remove some blocking of the ioloop
> Async Websocket API

- docs/src/pages/components-explorer/components/ffmpeg/index.mdx
- docs/src/pages/components-explorer/components/logger/index.mdx
- docs/src/pages/components-explorer/components/storage/config.json
- scripts/gen_docs/const.py
- viseron/components/storage/const.py
This pull request includes several documentation updates and a small bug fix. The most important changes include adding instructions for adding a timestamp to videos using FFmpeg, correcting a typo in multiple files, and updating import paths in the `const.py` script.
> Doc typos and FFmpeg timestamp example

- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .github/workflows/ci.yaml
A while back the mount for the config directory was removed due issues with it missing on the host.
It should now work properly to mount it since the config folder exists in the repo.
I did notice some strange behaviour with the mount not working since i already had files in the `/config` dir in the container, so make sure to fully clean your environment before rebuilding the devcontainer
> Mount config folder in repo to /config in devcontainer

- frontend/src/components/events/CameraPickerDialog.tsx
- frontend/src/components/events/EventDatePickerDialog.tsx
- frontend/src/components/events/EventPlayerCard.tsx
- frontend/src/components/events/EventTable.tsx
- frontend/src/components/events/EventTableItem.tsx
- frontend/src/components/events/EventsCameraGrid.tsx
- frontend/src/components/events/ExportDialog.tsx
- frontend/src/components/events/FloatingMenu.tsx
- frontend/src/components/events/Layouts.tsx
- frontend/src/components/events/SnapshotEvent.tsx
- frontend/src/components/events/SyncManager.tsx
- frontend/src/components/events/timeline/ProgressLine.tsx
- frontend/src/components/events/timeline/TimelinePlayer.tsx
- frontend/src/components/events/timeline/TimelineTable.tsx
- frontend/src/components/events/utils.tsx
- frontend/src/hooks/UseControlledInterval.tsx
- frontend/src/lib/api/cameras.ts
- frontend/src/pages/Events.tsx
- tests/components/webserver/api/v1/test_hls.py
- tests/domains/camera/test_fragmenter.py
- viseron/domains/camera/fragmenter.py
This PR includes a number of improvements to the Events page and making playback smoother.
- HLS playlists no longer set the EXT-X-GAP tag since HLS.js sometimes freezes when encountering the tag.
It will be reintroduced in a later release since HLS.js has fixed it in its current beta
- Fix a bug with the progress line positioning
- Dont error out when restarting Viseron while viewing the Events page
- Allow clicking on Events in the hover menus to seek to them
> Events and timeline navigation improvements

- docs/docs/documentation/configuration.md
- docs/docs/documentation/configuration/snapshots.md
- docs/src/pages/components-explorer/_domains/motion_detector/index.mdx
- docs/src/pages/components-explorer/_domains/object_detector/zones.mdx
- docs/src/pages/components-explorer/components/background_subtractor/config.json
- docs/src/pages/components-explorer/components/background_subtractor/index.mdx
- docs/src/pages/components-explorer/components/codeprojectai/config.json
- docs/src/pages/components-explorer/components/codeprojectai/index.mdx
- docs/src/pages/components-explorer/components/darknet/config.json
- docs/src/pages/components-explorer/components/darknet/index.mdx
- docs/src/pages/components-explorer/components/deepstack/config.json
- docs/src/pages/components-explorer/components/edgetpu/config.json
- docs/src/pages/components-explorer/components/edgetpu/index.mdx
- docs/src/pages/components-explorer/components/mog2/config.json
- docs/src/pages/components-explorer/components/mog2/index.mdx
- tests/components/codeprojectai/test_object_detector.py
- tests/helpers/test_filter.py
- viseron/components/nvr/nvr.py
- viseron/components/storage/const.py
- viseron/const.py
- viseron/domains/motion_detector/__init__.py
- viseron/domains/motion_detector/const.py
- viseron/domains/object_detector/__init__.py
- viseron/domains/object_detector/const.py
- viseron/domains/object_detector/detected_object.py
- viseron/domains/object_detector/zone.py
- viseron/helpers/filter.py
Changes the name from `trigger_recorder` to `trigger_event_recording` for clarity.
Functionality remains the same
> deprecate trigger_recorder in favor of trigger_event_recording

- docker/Dockerfile.dev
- docker/Dockerfile.tests
- docs/docs/documentation/configuration/recordings.mdx
- docs/docs/documentation/installation.mdx
- docs/src/pages/components-explorer/components/ffmpeg/config.json
- docs/src/pages/components-explorer/components/ffmpeg/index.mdx
- docs/src/pages/components-explorer/components/gstreamer/config.json
- docs/src/pages/components-explorer/components/logger/index.mdx
- rootfs/etc/cont-init.d/10-adduser
- tests/components/storage/test__init__.py
- tests/components/storage/test_config.py
- tests/components/storage/test_tier_handler.py
- tests/components/webserver/test_tiered_file_handler.py
- viseron/components/storage/__init__.py
- viseron/components/storage/alembic/versions/7b1f82f2ec39_move_clips_to_new_folder.py
- viseron/components/storage/config.py
- viseron/components/storage/const.py
- viseron/components/storage/jobs.py
- viseron/components/storage/queries.py
- viseron/components/storage/tier_handler.py
- viseron/components/storage/util.py
- viseron/components/webserver/api/v1/hls.py
- viseron/components/webserver/websocket_api/commands.py
- viseron/domains/camera/__init__.py
- viseron/domains/camera/config.py
- viseron/domains/camera/recorder.py
This PR changes the location of clips created by `create_event_clip: true` to `/event_clips`.
Mounting `/recordings` is therefore not necessarry any longer.
The configuration for specifying camera specific storage options has changed from
```yaml
ffmpeg: # or any other camera component
camera:
camera_one:
name: Camera 1
...
recorder:
storage:
tiers:
```
to:
```yaml
ffmpeg: # or any other camera component
camera:
camera_one:
name: Camera 1
...
storage:
recorder:
tiers:
```
making it identical to that of the `storage` component
> Rename /recordings to /event_clips

- docs/src/pages/components-explorer/components/telegram/_meta.tsx
- docs/src/types.ts
This PR adds a new "Notification" category to the components explorer to properly categorize notification-related components.
1. Added a new "notification" domain type in `docs/src/types.ts` with:
- Label: "Notification"
- Color: "#ff2a44" (red for Alert)
2. Updated Telegram component metadata to include the "notification" tag
<details><summary>Screenshot</summary>
<p>
</p>
</details>
> Add Notification Category to Components Explorer

- docs/src/pages/components-explorer/components/discord/_meta.tsx
- docs/src/pages/components-explorer/components/discord/config.json
- docs/src/pages/components-explorer/components/discord/index.mdx
- viseron/components/discord/__init__.py
- viseron/components/discord/const.py
This PR adds a new Discord component to Viseron that allows sending notifications to a Discord webhook when events are detected.
- **Notifications at key moments**:
1. **At the start of recording**: A notification message is always sent as soon as recording starts, with or without a thumbnail depending on configuration
2. **At the end of recording**: If video sending is enabled, a notification with the video is sent either:
- Complete, if the size limit isn't reached
- Truncated at the size limit, if reached
- **Configurable parameters**:
- Discord Webhook URL
- Thumbnail sending
- Video sending
- Detection label (default: "person")
- Per-camera configuration (ability to override global settings for each camera)
- **Respects Discord limits**:
- Configurable parameter for maximum video …
> Discord component for notifications

- docs/src/pages/components-explorer/components/gotify/_meta.tsx
- docs/src/pages/components-explorer/components/gotify/config.json
- docs/src/pages/components-explorer/components/gotify/index.mdx
- scripts/gen_docs/__main__.py
- viseron/components/gotify/__init__.py
- viseron/components/gotify/const.py
This PR adds a new Gotify notification component to Viseron that allows sending notifications to a Gotify server when recordings start.
- Send notifications to a Gotify server when recordings are triggered
- Configure notification priority (1-10)
- Filter notifications by object type (e.g., person, car, cat)
- Support for camera-specific configuration overrides
- Option to include thumbnail images of detected objects in notifications
The component can be configured in the Viseron configuration file:
```yaml
gotify:
gotify_url: "https://gotify.example.com"  # URL to your Gotify server
gotify_token: "YOUR_APPLICATION_TOKEN"     # Application token from Gotify
priority: 5                               # Priority of the notifications (1-10)
detection_label: "person,cat"             # Labels …
```
> Add Gotify notification component

- frontend/src/components/events/EventTable.tsx
- frontend/src/components/events/FilterMenu.tsx
- frontend/src/components/events/SnapshotEvent.tsx
- frontend/src/components/events/utils.tsx
New button on the Events page to group events from different cameras.
Makes it easier to get an overview of the events if many cameras are viewed
> allow for grouping events for different cameras

- frontend/src/components/settings/user/UserDialog.tsx
- frontend/src/lib/api/auth.ts
- frontend/src/lib/types.ts
- frontend/tests/utils/renderWithContext.tsx
- tests/components/webserver/api/v1/test_auth.py
- tests/components/webserver/test_auth.py
- viseron/components/webserver/api/v1/auth.py
- viseron/components/webserver/api/v1/cameras.py
- viseron/components/webserver/auth.py
- viseron/components/webserver/request_handler.py
- viseron/components/webserver/websocket_api/commands.py
This PR makes it possible to assign cameras per user.
Admins can choose what cameras each user can access using the User Management page.
The user will then not see the cameras at all in the UI and the API will not return them, even if somehow requested.
Some camera events may still slip through tho but that should not matter.
> assign cameras to users

- frontend/src/components/events/FilterMenu.tsx
- frontend/src/components/events/utils.tsx
- frontend/src/lib/types.ts
- viseron/components/webserver/api/v1/events.py
Add a new checkbox to the filter menu which controls wether the played back timestamp is adjusted by the configured lookback value or not
Closes #966
> add lookback adjustment when clicking on an event

- docs/docs/documentation/configuration/recordings.mdx
- frontend/src/pages/Events.tsx
Allows setting the timestamp which the Events page starts to play on load by using the query parameter `timestamp`.
The timestamp should be a UTC timestamp.
Example URL: `http://host.lan:8888/#/events?tab=timeline&date=2025-04-18&timestamp=1745001300`
Closes #942
> set requested timestamp from query parameter

- frontend/src/components/events/EventPlayerCard.tsx
- frontend/src/components/recording/RecordingCard.tsx
- frontend/src/components/recording/RecordingCardDaily.tsx
- frontend/src/components/recording/RecordingCardLatest.tsx
- frontend/src/lib/helpers.tsx
- frontend/src/lib/types.ts
- frontend/tests/lib/helpers.test.ts
- viseron/components/ffmpeg/camera.py
- viseron/components/ffmpeg/stream.py
- viseron/components/gstreamer/camera.py
- viseron/domains/camera/__init__.py
When using a substream that has different aspect ratio than the main stream, the aspect ratio of videoplayers was incorrectly set to the substreams resolution.
This PR fixes that
> expose main stream resolution to get correct aspect ratio for streams

- viseron/components/edgetpu/__init__.py
- viseron/components/edgetpu/object_detector.py
- viseron/components/nvr/nvr.py
- viseron/domains/motion_detector/__init__.py
- viseron/domains/object_detector/__init__.py
- viseron/helpers/subprocess_worker.py
Adds a new callback in motion/object detector, `result_failed_callback`, that is called from the `NVR` component when it waits for too long before retrieving a result.
EdgeTPU processes will be restarted after 10 failures has occured
> edgetpu restart on failure

- tests/domains/camera/test_recorder.py
- viseron/domains/camera/recorder.py
This pull request intends to address a timing issue when [concatenating fragments](https://github.com/roflcoopter/viseron/blob/0568e0ea7b768fc95cd4469e7402e87e7587bf9b/viseron/domains/camera/recorder.py#L369).  It results in an error [discussed here](https://github.com/roflcoopter/viseron/discussions/1010).
I have incorrectly diagnosed the problem a couple times but I think I have it figured out now.
1.  User has `create_event_clip` enabled
2. A recording completes before segments applicable to that recording have been written
3. ffmpeg is called for that recording however there are no segments available so it errors out
In theory this would also result in not taking into account all segments if a segment ends during the recording and another is started while recording is in progress. …
> fix timing issue with _concatenate_fragements

- .github/workflows/ci.yaml
Ultralytics depends on Pytorch which is causing out of space error in CI due to installing CUDA libraries.
This is an attempt to force CPU only install of Pytorch
> force pytorch CPU install in CI

- viseron/components/storage/__init__.py
- viseron/components/storage/jobs.py
Cleanup jobs were only running on the first tier. This fixes so that all tiers are checked.
> fix cleanup jobs to run on all tier paths

- docker/jetson-nano/Dockerfile.wheels
- docs/src/pages/components-explorer/components/yolo/index.mdx
- requirements-3.9.txt
- requirements.txt
Stop Ultralytics from being installed on the RPi3 as it is not supported.
Also pins Pillow to 11.1.0 to resolve a build error when building the Python 3.9 wheels
> RPi3 ignore ultralytics

- rootfs/usr/local/nginx/conf/proxy.conf
When running the container on Nintendo Switch (Jetson TX1) with host Fedora 42; the following issue occurs: `nginx: [emerg] unknown directive "ssl_early_data"` Looks similar to https://forum.mattermost.com/t/nginx-proxy-unknown-directive-ssl-early-data/12112
> nginx: proxy.conf: remove ssl_early_data

- docs/docs/documentation/installation.mdx
- docs/src/pages/components-explorer/components/ffmpeg/index.mdx
- docs/src/pages/components-explorer/components/hailo/index.mdx
- docs/src/pages/components-explorer/components/logger/index.mdx
- viseron/components/storage/jobs.py
- viseron/components/storage/tier_handler.py
- viseron/components/storage/util.py
- viseron/domains/camera/__init__.py
- viseron/domains/camera/fragmenter.py
A few fixes to the timelapse functionality introduced in #1104 
- Extract frames to a temporary folder instead of placing it in the tier folder, reducing some traffic
- Specifying seconds in the timelapse interval did not work since `calculate_age`  did not take seconds into account
- Add the new timelapse path to cleanup jobs
- Update docker docs to include timelapse volume
> Timelapse improvements

- docs/src/pages/components-explorer/_domains/object_detector/index.mdx
- docs/src/pages/components-explorer/_domains/object_detector/zones.mdx
Fix an error in the zone example yaml in the docs. Indentation was wrong and the component being viewed was not inserted
> fix object detector zone examples in the docs
